"""empty message

Revision ID: 1dcb11c0db95
Revises: c73a96cb0334
Create Date: 2016-06-30 15:05:11.864148

"""

# revision identifiers, used by Alembic.
revision = '1dcb11c0db95'
down_revision = 'c73a96cb0334'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def func(x):
    print "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    print x

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('price', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('product', 'slug',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'slug',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('price', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('price', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    ### end Alembic commands ###
