"""empty message

Revision ID: 385c54f96db0
Revises: c23e13780720
Create Date: 2016-07-13 14:17:10.923453

"""

# revision identifiers, used by Alembic.
revision = '385c54f96db0'
down_revision = 'c23e13780720'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('value', sa.Integer(), nullable=True))
    op.drop_column('price', 'price_int')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('price_int', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('price', 'value')
    ### end Alembic commands ###
