"""empty message

Revision ID: c23e13780720
Revises: 1bf81939a248
Create Date: 2016-07-13 14:13:18.651967

"""

# revision identifiers, used by Alembic.
revision = 'c23e13780720'
down_revision = '1bf81939a248'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('price_int', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'price_int')
    ### end Alembic commands ###
