"""empty message

Revision ID: c73a96cb0334
Revises: f13b8440d88f
Create Date: 2016-06-30 15:02:36.004759

"""

# revision identifiers, used by Alembic.
revision = 'c73a96cb0334'
down_revision = 'f13b8440d88f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('type', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'type')
    ### end Alembic commands ###
