"""empty message

Revision ID: ea03dc401c19
Revises: 385c54f96db0
Create Date: 2016-07-13 15:20:21.458061

"""

# revision identifiers, used by Alembic.
revision = 'ea03dc401c19'
down_revision = '385c54f96db0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'price')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    ### end Alembic commands ###
