"""empty message

Revision ID: fc2c48999cb2
Revises: 3254b45dba30
Create Date: 2016-07-01 18:17:29.041634

"""

# revision identifiers, used by Alembic.
revision = 'fc2c48999cb2'
down_revision = '3254b45dba30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('link', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'link')
    ### end Alembic commands ###
